export const ACCOUNT_MESSAGES = {
  mn: {
    login: 'Нэвтрэх',
    register: 'Бүртгүүлэх',
    profile: 'Миний мэдээлэл',
    trips: 'Миний аялал',
    logout: 'Гарах',
    welcome: 'Аяллаа үргэлжлүүлье',
    join: 'Таны дараагийн аялал эндээс',
    intro: 'Төлөвлөсөн аялал, сонгосон амралтын газар, захиалгаа нэг дор хадгалаарай.',
    loginHint: 'Бүртгэлтэй имэйл эсвэл утасны дугаараа оруулна уу.',
    registerHint: 'Нэр болон холбоо барих мэдээллээрээ бүртгүүлээрэй.',
    email: 'Имэйл',
    phone: 'Утасны дугаар',
    name: 'Таны нэр',
    namePlaceholder: 'Нэрээ оруулна уу',
    send: 'Код авах',
    verify: 'Баталгаажуулах',
    codeTitle: 'Кодоо оруулна уу',
    code: 'Баталгаажуулах код',
    sent: 'руу баталгаажуулах код илгээлээ.',
    demo: 'Демо горим · Мессеж илгээхгүй. Дурын 6 оронтой тоогоор үргэлжлүүлнэ.',
    resend: 'Дахин илгээх',
    editContact: 'Мэдээллээ засах',
    seconds: 'сек',
    working: 'Түр хүлээнэ үү…',
    noAccount: 'Бүртгэлгүй юу?',
    hasAccount: 'Бүртгэлтэй юу?',
    back: 'Нүүр рүү буцах',
    invalidContact: 'Зөв имэйл эсвэл Монголын 8 оронтой утасны дугаар оруулна уу.',
    invalidName: 'Нэрээ оруулна уу.',
    name_required: 'Бүртгүүлэхийн тулд нэрээ оруулна уу.',
    movedToRegister: 'Энэ мэдээллээр бүртгэл олдсонгүй. Доорх мэдээллээр шинээр бүртгүүлээрэй.',
    movedToLogin: 'Энэ мэдээллээр бүртгэл аль хэдийн байна. Нэвтэрч үргэлжлүүлээрэй.',
    invalidCode: 'Яг 6 оронтой тоо оруулна уу.',
    genericError: 'Мэдээллийг авахад алдаа гарлаа. Дахин оролдоно уу.',
    registration_required: 'Энэ мэдээллээр бүртгэл олдсонгүй. Бүртгүүлж үргэлжлүүлээрэй.',
    account_exists: 'Энэ мэдээллээр бүртгэлтэй байна. Нэвтэрч үргэлжлүүлээрэй.',
    account_unavailable: 'Энэ бүртгэлээр нэвтрэх боломжгүй байна.',
    code_expired: 'Кодын хугацаа дууссан байна. Дахин код аваарай.',
    resend_wait: 'Дахин код авахын өмнө түр хүлээнэ үү.',
    rateLimited: 'Хэт олон удаа оролдлоо. Нэг минутын дараа дахин оролдоно уу.',
    demo_auth_disabled: 'Кодоор нэвтрэх боломж одоогоор хаалттай байна.',
    loading: 'Уншиж байна…',
    retry: 'Дахин оролдох',
    newTrip: 'Аялал төлөвлөх',
    tripsHint: 'Төлөвлөсөн аялал болон захиалгууд тань энд хадгалагдана.',
    emptyTrips: 'Аяллын түүх тань эндээс эхэлнэ',
    emptyTripsHint: 'Хаашаа явахаа сонгоод анхны аяллаа төлөвлөөрэй.',
    details: 'Дэлгэрэнгүй',
    people: 'хүн',
    guests: 'Зочид',
    one: { people: 'хүн', nights: 'шөнө', rooms: 'өрөө / гэр' },
    nights: 'шөнө',
    rooms: 'өрөө / гэр',
    day: 'Өдөр',
    itinerary: 'Аяллын маршрут',
    stays: 'Сонгосон амралтын газрууд',
    bookings: 'Захиалгын мэдээлэл',
    bookingId: 'Захиалгын дугаар',
    checkIn: 'Ирэх',
    checkOut: 'Буцах',
    total: 'Нийт дүн',
    estimated: 'Төлөвлөсөн зардал',
    resume: 'Аяллаа үргэлжлүүлэх',
    pay: 'Төлбөрөө үргэлжлүүлэх',
    noBookings: 'Одоогоор баталгаажсан захиалга байхгүй. Аяллаа үргэлжлүүлж байраа захиалаарай.',
    invoices: 'Төлбөрийн түүх',
    invoice: 'Нэхэмжлэх',
    invoiceHint: 'Аяллын төлбөр, төлсөн нэхэмжлэхүүд.',
    emptyInvoices: 'Одоогоор төлбөрийн түүх байхгүй.',
    reference: 'Төлбөрийн дугаар',
    paidAt: 'Төлсөн огноо',
    method: 'Төлбөрийн үйлчилгээ',
    notProvided: 'Бүртгээгүй',
    saved: 'Аялал хадгалагдлаа. Хүссэн үедээ эндээс үргэлжлүүлээрэй.',
    dismiss: 'Хаах',
    viewTrip: 'Аяллын дэлгэрэнгүй харах',
    save: 'Аялал хадгалах',
    notFound: 'Энэ аялал олдсонгүй.',
    notFoundHint: 'Аялал устгагдсан эсвэл өөр бүртгэлд хамаарах байж магадгүй.',
    backToTrips: 'Миний аялал руу буцах',
    trip_locked: 'Энэ аяллын захиалга эхэлсэн байна. Миний аяллаас дэлгэрэнгүйг харна уу.',
    accountHint: 'Таны аяллын мэдээлэл, бүгд нэг дор.',
    contact: 'Холбоо барих мэдээлэл',
    status: {
      planned: 'Төлөвлөсөн',
      awaiting_payment: 'Төлбөр хүлээж байна',
      booked: 'Захиалсан',
      in_progress: 'Аялж байна',
      completed: 'Дууссан',
      cancelled: 'Цуцалсан',
      confirmed: 'Баталгаажсан',
      held: 'Түр хадгалсан',
      paid: 'Төлсөн',
      expired: 'Хугацаа дууссан',
      failed: 'Амжилтгүй',
      refunded: 'Буцаасан',
      approved_by_user: 'Зөвшөөрсөн',
      quoted: 'Үнийн санал',
      open: 'Төлбөр хүлээж байна',
    },
  },
  en: {
    login: 'Sign in',
    register: 'Create account',
    profile: 'My profile',
    trips: 'My trips',
    logout: 'Sign out',
    welcome: 'Your journey continues',
    join: 'Your next journey starts here',
    intro: 'Keep your itineraries, favourite stays and bookings together in one place.',
    loginHint: 'Enter the email or phone number you registered with.',
    registerHint: 'Create an account with your name and contact details.',
    email: 'Email',
    phone: 'Phone number',
    name: 'Your name',
    namePlaceholder: 'Enter your name',
    send: 'Get code',
    verify: 'Verify & continue',
    codeTitle: 'Enter your code',
    code: 'Verification code',
    sent: 'We sent a verification code to',
    demo: 'Demo mode · No message is sent. Enter any 6-digit number to continue.',
    resend: 'Resend code',
    editContact: 'Edit contact details',
    seconds: 's',
    working: 'Please wait…',
    noAccount: 'New here?',
    hasAccount: 'Already have an account?',
    back: 'Back to home',
    invalidContact: 'Enter a valid email or an 8-digit Mongolian phone number.',
    invalidName: 'Enter your name.',
    name_required: 'Enter your name to create an account.',
    movedToRegister: 'No account uses these details yet. Create one below to continue.',
    movedToLogin: 'An account already uses these details. Sign in to continue.',
    invalidCode: 'Enter exactly 6 digits.',
    genericError: 'Something went wrong. Please try again.',
    registration_required: 'No account found. Create an account to continue.',
    account_exists: 'This account already exists. Sign in to continue.',
    account_unavailable: 'This account is unavailable.',
    code_expired: 'Your code has expired. Request a new one.',
    resend_wait: 'Please wait before requesting another code.',
    rateLimited: 'Too many attempts. Please try again in a minute.',
    demo_auth_disabled: 'Code sign-in is currently unavailable.',
    loading: 'Loading…',
    retry: 'Try again',
    newTrip: 'Plan a trip',
    tripsHint: 'Your itineraries and bookings, ready when you are.',
    emptyTrips: 'Your travel story starts here',
    emptyTripsHint: 'Choose a destination and plan your first journey.',
    details: 'View details',
    people: 'guests',
    guests: 'Guests',
    one: { people: 'guest', nights: 'night', rooms: 'room / ger' },
    nights: 'nights',
    rooms: 'rooms / gers',
    day: 'Day',
    itinerary: 'Your itinerary',
    stays: 'Selected stays',
    bookings: 'Booking details',
    bookingId: 'Booking reference',
    checkIn: 'Check-in',
    checkOut: 'Check-out',
    total: 'Total',
    estimated: 'Estimated cost',
    resume: 'Continue planning',
    pay: 'Continue to payment',
    noBookings: 'No confirmed bookings yet. Continue your trip to reserve your stay.',
    invoices: 'Payment history',
    invoice: 'Invoice',
    invoiceHint: 'Your trip payments and paid invoices.',
    emptyInvoices: 'No payments yet.',
    reference: 'Payment reference',
    paidAt: 'Paid on',
    method: 'Payment provider',
    notProvided: 'Not provided',
    saved: 'Trip saved. Pick it up here whenever you are ready.',
    dismiss: 'Dismiss',
    viewTrip: 'View trip details',
    save: 'Save trip',
    notFound: 'This trip could not be found.',
    notFoundHint: 'It may have been removed or belong to a different account.',
    backToTrips: 'Back to my trips',
    trip_locked: 'This trip already has a checkout. View its details in My trips.',
    accountHint: 'All your travel details, in one place.',
    contact: 'Contact details',
    status: {
      planned: 'Planned',
      awaiting_payment: 'Awaiting payment',
      booked: 'Booked',
      in_progress: 'In progress',
      completed: 'Completed',
      cancelled: 'Cancelled',
      confirmed: 'Confirmed',
      held: 'Reserved',
      paid: 'Paid',
      expired: 'Expired',
      failed: 'Failed',
      refunded: 'Refunded',
      approved_by_user: 'Approved',
      quoted: 'Quoted',
      open: 'Awaiting payment',
    },
  },
} as const
