import type { PlanWarning } from '~/types/trip-plan'
import type { AppLocale } from '~/types/trip-planner'

export const PLAN_MESSAGES = {
  mn: {
    title: 'Таны аяллын хөтөлбөр',
    loading: 'Хөтөлбөрийг ачаалж байна...',
    notFound: 'Энэ хөтөлбөр олдсонгүй эсвэл хугацаа нь дууссан (24 цаг). Шинээр үүсгэнэ үү.',
    backToPlanner: 'Шинэ хөтөлбөр үүсгэх',
    version: 'Хувилбар',
    places: 'Таны хүссэн газрууд',
    placeIncluded: 'Хөтөлбөрт орсон',
    placeUnresolved: 'Манай мэдээллийн санд олдсонгүй',
    day: 'өдөр',
    via: 'Замдаа',
    freeDay: 'Чөлөөт өдөр',
    stay: 'Хонох газар',
    nights: 'шөнө',
    units: 'ш',
    events: 'Ойролцоох эвент',
    eventsBookApart: 'Эвентийн захиалга тусдаа.',
    eventApart: 'Захиалга тусдаа',
    eventPhone: 'Утас',
    eventSite: 'Холбоос',
    sameStay: 'Энэ шөнө өмнөх буудалдаа',
    onePlaceOneStay:
      '{place} дээрх {nights} шөнө нэг буудал. Өөр газарт шөнө шилжүүлээгүй бол хоёр буудал сонгогдохгүй.',
    oneStayForNights: 'Энэ {nights} шөнийг нэг буудалд өнгөрүүлнэ. Нэгийг нь сонгоно.',
    prevPhoto: 'Өмнөх зураг',
    nextPhoto: 'Дараагийн зураг',
    enlargePhoto: 'Зургийг томруулах',
    closePhoto: 'Хаах',
    free: 'Үнэгүй',
    totals: 'Нийт үнэ (ойролцоо)',
    staysTotal: 'Буудал',
    eventsTotal: 'Эвент (захиалга тусдаа)',
    total: 'Нийт',
    budget: 'Төсөв',
    noLimit: 'Хязгааргүй',
    photo: 'Зураг',
    reviseLabel: 'Өөрчлөх зүйл байна уу?',
    revising: 'Шинэчилж байна...',
    chatPlaceholder: 'Юуг өөрчлөх вэ? Жишээ: Говийг хас',
    chatSend: 'Илгээх',
    chatRevised: 'Хөтөлбөрийг шинэчиллээ',
    chatShow: 'Яриаг харуулах',
    chatHide: 'Яриаг нуух',
    changesSoFar: 'Таны өмнөх өөрчлөлтүүд',
    draft: 'Энэ бол ноорог. Таалагдах хүртлээ өдөр бүр дээрээ хоногоо шилжүүлж, буудлаа сольж болно.',
    changeStay: 'Буудлаа солих',
    hideStays: 'Буудлын жагсаалтыг хаах',
    mealsIncluded: 'Хоолтой',
    kmAway: '{km} км',
    book: 'Энэ хөтөлбөрөөр захиалах',
    booking: 'Буудлуудыг түр барьж байна...',
    bookHint: 'Буудлууд 15 минут таны нэр дээр баригдана. Дараагийн алхамд төлбөрөө баталгаажуулна.',
    signInToBook: 'Захиалахын тулд нэвтэрнэ үү',
    nothingToBook: 'Энэ хөтөлбөрт захиалах буудал алга.',
    tooShortToBook: 'Энэ хугацаанд очиж ирэх боломжгүй тул захиалахгүй.',
    notEnoughTime:
      '{place} хүртэл нэг талдаа ойролцоогоор {hours} цаг явна. {nights} хоногт очиж, хоноод, буцаж ирэх боломжгүй — замд өнгөрнө. Хамгийн багадаа {minNights} хоног хэрэгтэй.',
    staysChanged: 'Зарим буудал дүүрчихсэн тул ойролцоох өөр буудлаар сольлоо. Шалгаад дахин захиална уу.',
    plannerDown: 'Төлөвлөгч түр ажиллахгүй байна. Хэсэг хүлээгээд дахин оролдоно уу.',
    genericError: 'Алдаа гарлаа. Дахин оролдоно уу.',
    warnings: {
      unresolved_place: 'Зарим газрыг танисангүй. Өөр нэрээр эсвэл ойролцоох газраар нь бичээд үзээрэй.',
      no_availability: 'Зарим шөнө сул буудал олдсонгүй (буудлын мэдээлэл 10/01–10/31 хооронд байгаа).',
      over_budget: 'Нийт үнэ таны төсвөөс давж байна.',
      too_many_places: 'Хугацаанд бүх газарт хонох боломжгүй тул заримд нь замдаа саатна.',
    } satisfies Record<PlanWarning, string>,
  },
  en: {
    title: 'Your itinerary',
    loading: 'Loading the itinerary...',
    notFound: 'This itinerary was not found or has expired (24 hours). Please create a new one.',
    backToPlanner: 'Create a new itinerary',
    version: 'Version',
    places: 'Places you asked for',
    placeIncluded: 'In the plan',
    placeUnresolved: 'Not found in our catalog',
    day: 'Day',
    via: 'On the way',
    freeDay: 'Free day',
    stay: 'Stay',
    nights: 'nights',
    units: '×',
    events: 'Nearby events',
    eventsBookApart: 'Events are booked separately. The button below holds the stays only.',
    eventApart: 'Booked separately',
    eventPhone: 'Phone',
    eventSite: 'Link',
    sameStay: 'Same stay as the night before',
    onePlaceOneStay:
      'All {nights} nights at {place} use one stay. A second stay is chosen only when a night moves to another place.',
    oneStayForNights: 'These {nights} nights are one stay. Choose one.',
    prevPhoto: 'Previous photo',
    nextPhoto: 'Next photo',
    enlargePhoto: 'Enlarge photo',
    closePhoto: 'Close',
    free: 'Free',
    totals: 'Estimated total',
    staysTotal: 'Stays',
    eventsTotal: 'Events (booked separately)',
    total: 'Total',
    budget: 'Budget',
    noLimit: 'No limit',
    photo: 'Photo',
    reviseLabel: 'Anything to change?',
    revising: 'Updating...',
    chatPlaceholder: 'What should change? e.g. skip the Gobi',
    chatSend: 'Send',
    chatRevised: 'Itinerary updated',
    chatShow: 'Show the conversation',
    chatHide: 'Hide the conversation',
    changesSoFar: 'Your changes so far',
    draft: 'This is a draft. Move nights and swap stays on each day until it feels right.',
    changeStay: 'Change stay',
    hideStays: 'Hide stays',
    mealsIncluded: 'Meals included',
    kmAway: '{km} km',
    book: 'Book this itinerary',
    booking: 'Holding your stays...',
    bookHint: 'Your stays are held for 15 minutes; you approve the payment on the next step.',
    signInToBook: 'Sign in to book',
    nothingToBook: 'This itinerary has no stays to book.',
    tooShortToBook: 'This trip does not fit the dates, so it cannot be booked.',
    notEnoughTime:
      "{place} is about {hours} hours' drive one way. {nights} nights is not enough to get there, stay, and come back — the days would be spent driving. At least {minNights} nights are needed.",
    staysChanged: 'Some stays filled up, so nearby ones were picked instead. Please check and book again.',
    plannerDown: 'The planner is unavailable right now. Please try again in a moment.',
    genericError: 'Something went wrong. Please try again.',
    warnings: {
      unresolved_place: 'Some places were not recognised. Try another name or a place nearby.',
      no_availability: 'Some nights have no free stay (stay data covers Oct 1–31).',
      over_budget: 'The total is over your budget.',
      too_many_places: 'Not every place gets a night in this time; some are visited on the way.',
    } satisfies Record<PlanWarning, string>,
  },
} as const

export type PlanMessages = (typeof PLAN_MESSAGES)[AppLocale]

export const STAY_TYPE_LABELS: Record<string, Record<AppLocale, string>> = {
  ger_camp: { mn: 'Гэр бааз', en: 'Ger camp' },
  guesthouse: { mn: 'Гэр буудал', en: 'Guesthouse' },
  hotel: { mn: 'Зочид буудал', en: 'Hotel' },
  house: { mn: 'Байшин', en: 'House' },
}
