import { BRAND } from '~/constants/brand'
import type { AppLocale, TripPlannerMessages } from '~/types/trip-planner'

export const VOICE_METER_DELAYS_MS = [0, 150, 300, 450, 200] as const

export const TRIP_PLANNER_MESSAGES: Record<AppLocale, TripPlannerMessages> = {
  mn: {
    documentTitle: `${BRAND.name}: аяллын хөтөлбөр`,
    languageGroupLabel: 'Хэл',
    heroTitle: 'Монголоор аялах хөтөлбөрөө төлөвлөе',
    heroSubtitle:
      'Юу үзэж, юу хиймээр байгаагаа бичих эсвэл хэлээрэй. Бид өдөр бүрийн маршрут, захиалах боломжтой буудлыг санал болгоно.',
    requestLabel: 'Хаашаа аялмаар байна?',
    requestPlaceholder: 'Хаашаа, хэдүүлээ, хэдэн хоног аялах вэ?',
    tapToSpeak: 'Дуугаар оруулах',
    listening: 'Сонсож байна… зогсоохын тулд дахин дарна уу',
    transcribing: 'Яриаг текст болгож байна…',
    voiceFailed: 'Дуу танигдсангүй. Дахин оролдоно уу.',
    voiceDenied: 'Микрофон ашиглах зөвшөөрөл өгөөгүй байна. Browser-ийн тохиргооноос зөвшөөрнө үү.',
    voiceUnavailable: 'Яриа таних үйлчилгээ одоогоор тохируулагдаагүй байна. Бичиж оруулна уу.',
    voiceButtonLabel: 'Монгол хэлээр дуут оруулалт',
    generate: 'Илгээх',
    retry: 'Дахин оролдох',
    chat: {
      ask: {
        place: 'Хаашаа аялах вэ?',
        guests: 'Сайхан санаа байна. Хэдүүлээ явах вэ?',
        dates: 'Хэдэн сарын хэднээс хэдний хооронд явах вэ? Жишээ нь «10 сарын 5-наас 12».',
        budget: 'Нийт төсөв хэр орчим бэ?',
      },
      choices: {
        fromDate: 'Эхлэх',
        toDate: 'Дуусах',
        useDates: 'Эдгээр өдрөөр',
        datesInvalid: 'Дуусах өдөр эхлэхээс өмнө, эсвэл 30 хоногоос урт байна.',
        guestSuffix: 'хүн',
        guests: [1, 2, 3, 4, 5, 6, 8],
        budgets: [
          { label: '1 сая дотор', value: '1 сая дотор' },
          { label: '2 сая дотор', value: '2 сая дотор' },
          { label: '3.5 сая дотор', value: '3.5 сая дотор' },
          { label: '5 сая дотор', value: '5 сая дотор' },
        ],
        places: [
          { label: 'Хөвсгөл нуур', value: 'Хөвсгөл нуур' },
          { label: 'Горхи-Тэрэлж', value: 'Горхи-Тэрэлж' },
          { label: 'Увс нуур', value: 'Увс нуур' },
          { label: 'Хархорин', value: 'Хархорин' },
        ],
      },
      extra: 'Нэмж оруулах мэдээлэл байна уу? Байвал доор бичээрэй.',
      noExtra: 'Байхгүй',
      offTopic: 'Уучлаарай, би аяллын хөтөлбөр гаргахад туслана. Энэ асуултаа дуусгая.',
      offTopicReady: 'Уучлаарай, би аяллын хөтөлбөр гаргахад туслана. Бэлэн бол доорх товчийг дарна уу.',
      ready: 'За, мэдээлэл бүрдлээ. Хөтөлбөр гаргах уу?',
      generatePlan: 'Хөтөлбөр гаргах',
      planning: 'Хөтөлбөр бэлдэж байна.',
      revising: 'За, хөтөлбөрийг шинэчилж байна.',
      planned: 'Танд зориулсан хөтөлбөр бэлэн. Өөрчлөх зүйл байвал доор бичээрэй.',
      revised: 'Шинэчиллээ. Өөр юм өөрчлөх үү?',
      agentName: `${BRAND.name} агент`,
      replyPlaceholder: 'Хариулт эсвэл өөрчлөлтөө бичих',
      newTrip: 'Шинэ аялал',
      openPlan: 'Дэлгэрэнгүй, захиалах',
      days: 'өдөр',
      total: 'Нийт',
    },
    errors: {
      planner_unavailable: 'Төлөвлөгч түр ажиллахгүй байна. Хэсэг хүлээгээд дахин оролдоно уу.',
      error: 'Хөтөлбөр үүсгэж чадсангүй. Дахин оролдоно уу.',
    },
  },
  en: {
    documentTitle: `${BRAND.name}: plan your trip`,
    languageGroupLabel: 'Language',
    heroTitle: 'Plan your journey through Mongolia',
    heroSubtitle:
      'Tell us what you would like to see and do. We will suggest a day-by-day route with stays you can book.',
    requestLabel: 'Where would you like to go?',
    requestPlaceholder: 'Where to, how many of you, and for how long?',
    tapToSpeak: 'Speak your request',
    listening: 'Listening… tap again to stop',
    transcribing: 'Turning your speech into text…',
    voiceFailed: 'Could not hear that. Please try again.',
    voiceDenied: 'Microphone access is blocked. Allow it in your browser settings.',
    voiceUnavailable: 'Speech input is not set up yet. Please type your request.',
    voiceButtonLabel: 'Speak your request',
    generate: 'Send',
    retry: 'Try again',
    chat: {
      ask: {
        place: 'Where would you like to go?',
        guests: 'Sounds lovely. How many of you are going?',
        dates: 'Which dates, from which day to which day? For example "Oct 5 to 12".',
        budget: 'Roughly what is your total budget?',
      },
      choices: {
        fromDate: 'From',
        toDate: 'To',
        useDates: 'Use these dates',
        datesInvalid: 'The end date is before the start, or the trip is longer than 30 days.',
        guestSuffix: 'people',
        guests: [1, 2, 3, 4, 5, 6, 8],
        budgets: [
          { label: 'Within 1 million', value: 'Within 1 million' },
          { label: 'Within 2 million', value: 'Within 2 million' },
          { label: 'Within 3.5 million', value: 'Within 3.5 million' },
          { label: 'Within 5 million', value: 'Within 5 million' },
        ],
        places: [
          { label: 'Lake Khövsgöl', value: 'Lake Khövsgöl' },
          { label: 'Terelj', value: 'Terelj' },
          { label: 'Lake Uvs', value: 'Lake Uvs' },
          { label: 'Kharkhorin', value: 'Kharkhorin' },
        ],
      },
      extra: 'Anything else to add before the itinerary? Write it below if so.',
      noExtra: 'Nothing else',
      offTopic: 'I can help you plan the trip. Let us finish this question first.',
      offTopicReady: 'I can help you plan the trip. When you are ready, press the button below.',
      ready: 'That is everything I need. Shall I create the itinerary?',
      generatePlan: 'Create the itinerary',
      planning: 'Preparing your itinerary.',
      revising: 'Sure, updating the itinerary.',
      planned: 'Here is an itinerary for you. Tell me below if you want anything changed.',
      revised: 'Updated. Anything else to change?',
      agentName: `${BRAND.name} agent`,
      replyPlaceholder: 'Reply or ask for a change',
      newTrip: 'New trip',
      openPlan: 'Details and booking',
      days: 'days',
      total: 'Total',
    },
    errors: {
      planner_unavailable: 'The planner is unavailable right now. Please try again in a moment.',
      error: 'Could not create the itinerary. Please try again.',
    },
  },
}
