import type { PlanWarning } from '~/types/trip-plan'
import type { AppLocale } from '~/types/trip-planner'

export const PLAN_MESSAGES = {
  mn: {
    title: 'Таны аяллын хөтөлбөр',
    loading: 'Хөтөлбөрийг ачаалж байна...',
    notFound: 'Энэ хөтөлбөр олдсонгүй эсвэл хугацаа нь дууссан (24 цаг). Шинээр үүсгэнэ үү.',
    backToPlanner: 'Шинэ хөтөлбөр үүсгэх',
    version: 'Хувилбар',
    places: 'Таны хүссэн газрууд',
    placeIncluded: 'Хөтөлбөрт орсон',
    placeUnresolved: 'Манай мэдээллийн санд олдсонгүй',
    day: 'өдөр',
    via: 'Замдаа',
    freeDay: 'Чөлөөт өдөр',
    stay: 'Хонох газар',
    nights: 'шөнө',
    units: 'ш',
    noStay: 'Энэ шөнө сул буудал олдсонгүй',
    events: 'Энэ өдөр болох арга хэмжээ',
    free: 'Үнэгүй',
    totals: 'Нийт үнэ (ойролцоо)',
    staysTotal: 'Буудал',
    eventsTotal: 'Арга хэмжээний тасалбар',
    total: 'Нийт',
    budget: 'Төсөв',
    noLimit: 'Хязгааргүй',
    photo: 'Зураг',
    reviseLabel: 'Өөрчлөх зүйл байна уу?',
    revisePlaceholder: 'Жишээ: Хөвсгөлд 3 хонъё, Говийг хас, Тэрхийн Цагаан нуурыг нэм...',
    revise: 'Хөтөлбөрийг шинэчлэх',
    revising: 'Шинэчилж байна...',
    changesSoFar: 'Таны өмнөх өөрчлөлтүүд',
    book: '100% таалагдсан — ойролцоох гэр/буудлаа захиалах',
    booking: 'Буудлуудыг түр барьж байна...',
    bookHint: 'Буудлууд 15 минут таны нэр дээр баригдана. Дараагийн алхамд төлбөрөө баталгаажуулна.',
    signInToBook: 'Захиалахын тулд нэвтэрнэ үү',
    nothingToBook: 'Энэ хөтөлбөрт захиалах буудал алга.',
    staysChanged: 'Зарим буудал дүүрчихсэн тул ойролцоох өөр буудлаар сольлоо. Шалгаад дахин захиална уу.',
    plannerDown: 'AI төлөвлөгч түр ажиллахгүй байна. Хэсэг хүлээгээд дахин оролдоно уу.',
    genericError: 'Алдаа гарлаа. Дахин оролдоно уу.',
    warnings: {
      unresolved_place: 'Зарим газрыг танисангүй. Өөр нэрээр эсвэл ойролцоох газраар нь бичээд үзээрэй.',
      no_availability: 'Зарим шөнө сул буудал олдсонгүй (буудлын мэдээлэл 10/01–10/14 хооронд байгаа).',
      over_budget: 'Нийт үнэ таны төсвөөс давж байна.',
      too_many_places: 'Хугацаанд бүх газарт хонох боломжгүй тул заримд нь замдаа саатна.',
    } satisfies Record<PlanWarning, string>,
  },
  en: {
    title: 'Your itinerary',
    loading: 'Loading the itinerary...',
    notFound: 'This itinerary was not found or has expired (24 hours). Please create a new one.',
    backToPlanner: 'Create a new itinerary',
    version: 'Version',
    places: 'Places you asked for',
    placeIncluded: 'In the plan',
    placeUnresolved: 'Not found in our catalog',
    day: 'Day',
    via: 'On the way',
    freeDay: 'Free day',
    stay: 'Stay',
    nights: 'nights',
    units: '×',
    noStay: 'No free stay found for this night',
    events: 'Events that day',
    free: 'Free',
    totals: 'Estimated total',
    staysTotal: 'Stays',
    eventsTotal: 'Event tickets',
    total: 'Total',
    budget: 'Budget',
    noLimit: 'No limit',
    photo: 'Photo',
    reviseLabel: 'Anything to change?',
    revisePlaceholder: 'e.g. 3 nights at Khövsgöl, skip the Gobi, add Terkhiin Tsagaan Lake...',
    revise: 'Update the itinerary',
    revising: 'Updating...',
    changesSoFar: 'Your changes so far',
    book: 'I love it — book the nearby gers/hotels',
    booking: 'Holding your stays...',
    bookHint: 'Your stays are held for 15 minutes; you approve the payment on the next step.',
    signInToBook: 'Sign in to book',
    nothingToBook: 'This itinerary has no stays to book.',
    staysChanged: 'Some stays filled up, so nearby ones were picked instead. Please check and book again.',
    plannerDown: 'The AI planner is unavailable right now. Please try again in a moment.',
    genericError: 'Something went wrong. Please try again.',
    warnings: {
      unresolved_place: 'Some places were not recognised. Try another name or a place nearby.',
      no_availability: 'Some nights have no free stay (stay data covers Oct 1–14).',
      over_budget: 'The total is over your budget.',
      too_many_places: 'Not every place gets a night in this time; some are visited on the way.',
    } satisfies Record<PlanWarning, string>,
  },
} as const

export type PlanMessages = (typeof PLAN_MESSAGES)[AppLocale]

export const STAY_TYPE_LABELS: Record<string, Record<AppLocale, string>> = {
  ger_camp: { mn: 'Гэр бааз', en: 'Ger camp' },
  guesthouse: { mn: 'Гэр буудал', en: 'Guesthouse' },
  hotel: { mn: 'Зочид буудал', en: 'Hotel' },
  house: { mn: 'Байшин', en: 'House' },
}
